### PR TITLE
Add Composer instructions

### PR DESCRIPTION
**Pull request by Sjors**
Without this I get an error about not being able to load `vendor/autoload.php`

### CODE REVIEW

**Comment by shesek** [comment]
The instructions assume you've downloaded the `woocommerce-gateway-lightning.zip` file available under [releases](https://github.com/ElementsProject/woocommerce-gateway-lightning/releases), which we already [pre-package](https://github.com/ElementsProject/woocommerce-gateway-lightning/blob/master/build.sh) with the vendor directory and everything else you need.

Can you try installing using that and see if that works?

https://github.com/ElementsProject/woocommerce-gateway-lightning/releases/download/v0.1.5/woocommerce-gateway-lightning.zip

**Comment by Sjors** [comment]
Ah, it's Github being weird: if you click on the zip file under releases it downloads an archive which includes the vendor directory. However at least on OSX that archive ends up in extracted form in the Downloads directory, meaning you can't upload it to Wordpress. 

But if you right-click on the zip file and click save as, it downloads as a zip file. That can be uploaded to Wordpress, but for some reason that zip doesn't contain the vendor dir.

**Comment by shesek** [comment]
Are you sure you aren't downloading `Source code (zip)` instead of the attached `woocommerce-gateway-lightning.zip` file?

**Comment by Sjors** [comment]
Maybe, either way, the vendor dir is indeed in the release archive, so closing this...

**Pull request closed without merging**
